name: Android Build

on:
  push:
    branches:
      - '*'
  watch:
    types: [started]

jobs:
  build:

    runs-on: ubuntu-latest

    if: github.actor == github.event.repository.owner.login

    steps:
      - name: Checking out repository
        uses: actions/checkout@v2

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Run test
        run: ./gradlew test

      - name: Build Debug APK
        run: ./gradlew assembleDebug
        
      - name: Get Debug APK
        uses: actions/upload-artifact@v1
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
          
      - name: Build Signed APK
        run: ./gradlew assembleRelease
        
      - name: Sign Android release
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          
      - name: Upload Release Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release
          path: ${{ env.SIGNED_RELEASE_FILE }}
   
      - name: Send email if upload release artifact fails
        if: always() # set always
      - uses: technote-space/workflow-conclusion-action@v1
        with:
          status: failure
        if: env.WORKFLOW_CONCLUSION == 'failure'
      - uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Github Actions job result
          body: Build job of ${{github.repository}} is incomplete, Release APK missing OMG!
          to: ${{secrets.MAIL_USERNAME}}
          from: ${{secrets.MAIL_USERNAME}}
                
      - name: Check debug apk existence
        id: check_debug
        uses: andstor/file-existence-action@v1
        with:
          files: "app-debug.apk"
          
      - name: Missing Debug APK
        if: steps.check_debug.outputs.files_exists == 'false'
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Github Actions job result
          body: Build job of ${{github.repository}} is incomplete, Debug APK missing!
          to: ${{secrets.MAIL_USERNAME}}
          from: ${{secrets.MAIL_USERNAME}}
          
      - name: Contains Debug APK
        if: steps.check_debug.outputs.files_exists == 'true'
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Github Actions job result
          body: Build job of ${{github.repository}} completed successfully, Debug APK exists!
          to: ${{secrets.MAIL_USERNAME}}
          from: ${{secrets.MAIL_USERNAME}}
          
      - name: Check release apk existence
        id: check_release
        uses: andstor/file-existence-action@v1
        with:
          files: "app-release.aab"  
        
      - name: Missing Release APK
        if: steps.check_release.outputs.files_exists == 'false'
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Github Actions job result
          body: Build job of ${{github.repository}} is incomplete, Release APK missing!
          to: ${{secrets.MAIL_USERNAME}}
          from: ${{secrets.MAIL_USERNAME}}
          
      - name: Contains Release APK
        if: steps.check_release.outputs.files_exists == 'true'
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Github Actions job result
          body: Build job of ${{github.repository}} completed successfully, Release APK exists!
          to: ${{secrets.MAIL_USERNAME}}
          from: ${{secrets.MAIL_USERNAME}}
          

